### ISSUE TITLE
Attachments not being found

### ISSUE THREAD

**Issue by gl31415** [anirvan/yahoo-group-archive-tools#5]
First, many thanks for this fantastic tool. Lovely work.

The issue is that no attachments are being found, despite them being present in both the attachments and topics directories. 

In the case of the attachments directory everything seems to be correctly named
/attachments/attachmentId/fileId-filename
– and the info seems to be correct in the corresponding attachmentinfo.json file.

(I'm using your tools on output produced by IgnoredAmbience's version of the archiver.)

Could you look into this?

**Comment by anirvan** [comment]
@gl31415 The script gets information about which email goes with which attachment, and what those attachments are named, by looking at files named `/email/[email id].json`.

Do you have files like `/email/2.json` in your backup?

**Comment by anirvan** [comment]
@gl31415 Just to be safe, I updated the script to use data from `/topics/[topic-id]/json` if `/email/[email-id].json` doesn't exist. In case you're missing `/email/[email-id].json`, does this fix the problem?

**Comment by gl31415** [comment]
Anirvan, thanks.

 I'm afraid it's still not finding the attachments. I do have an /email folder, with files named, for example, 
`1_raw.json `
`2_raw.json` .... 
(Not sure if this difference in naming is a problem?)

Just to clarify the structure of the topics folder. I typically have a folder: 
`/topics/21516_attachments`
containing the actual attachments
while
` /topics/21516.json`
contains the info on the naming of those files. (You wrote` /topics/[topic-id]/json`, but the /json was just a typo?)

Adding to all this, yahoo/verizon are now making the downloading of data so slow as to making the archiving of any further groups impractical.  Lovely.

Again, thanks!

**Comment by anirvan** [comment]
That's weird. The latest version of the code should be pulling out information on /topics/[number].json and grabbing attachments from /topics/[number]_attachments

Would you be willing to privately share your list data, so I can test my code on it? Feel free to send a dropbox/etc. link to my first name at my last name dot net.

**Comment by anirvan** [comment]
I'm closing and merging this issue with #2
